# Generated by Django 4.1.3 on 2022-12-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regloginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table=None,
        ),
    ]
