# Generated by Django 4.1.3 on 2022-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=11)),
                ('profile_pic', models.ImageField(upload_to='profilepic')),
                ('passw', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SignUp',
            },
        ),
    ]
