# Generated by Django 4.1.3 on 2022-11-25 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
